updates:
  - directory: /
    open-pull-requests-limit: 3
    package-ecosystem: pip
    schedule:
      interval: weekly
    labels:
      - "dependabot"
      - "dependencies"
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"